### ISSUE TITLE
Why is EnhancedQueueExecutorBase5 licensed differently?

### ISSUE THREAD

**Issue by bmccutchon** [jbossas/jboss-threads#130]
I was wondering why [EnhancedQueueExecutorBase5](https://github.com/jbossas/jboss-threads/blob/main/src/main/java/org/jboss/threads/EnhancedQueueExecutorBase5.java) is licensed under the LGPL rather than Apache 2.

**Comment by dmlloyd** [comment]
It's an error. It must have been missed by the tool I used to scan for notices.
